# coding: utf-8

"""
    Document API for Dummies

    A simple API to learn the basics and experiment with documents.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_create_document_documents_post(self) -> None:
        """Test case for create_document_documents_post

        Create Document
        """
        pass

    def test_delete_document_documents_document_id_delete(self) -> None:
        """Test case for delete_document_documents_document_id_delete

        Delete Document
        """
        pass

    def test_get_document_by_id_documents_document_id_get(self) -> None:
        """Test case for get_document_by_id_documents_document_id_get

        Get Document By Id
        """
        pass

    def test_get_documents_documents_get(self) -> None:
        """Test case for get_documents_documents_get

        Get Documents
        """
        pass

    def test_update_document_documents_document_id_put(self) -> None:
        """Test case for update_document_documents_document_id_put

        Update Document
        """
        pass


if __name__ == '__main__':
    unittest.main()
