# coding: utf-8

"""
    Document API for Dummies

    A simple API to learn the basics and experiment with documents.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.document_type import DocumentType

class TestDocumentType(unittest.TestCase):
    """DocumentType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDocumentType(self):
        """Test DocumentType"""
        # inst = DocumentType()

if __name__ == '__main__':
    unittest.main()
