# coding: utf-8

"""
    Document API for Dummies

    A simple API to learn the basics and experiment with documents.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.document_create import DocumentCreate

class TestDocumentCreate(unittest.TestCase):
    """DocumentCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DocumentCreate:
        """Test DocumentCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DocumentCreate`
        """
        model = DocumentCreate()
        if include_optional:
            return DocumentCreate(
                name = 'G012',
                owner = 'G012',
                type = 'PDF'
            )
        else:
            return DocumentCreate(
                name = 'G012',
                owner = 'G012',
                type = 'PDF',
        )
        """

    def testDocumentCreate(self):
        """Test DocumentCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
