# coding: utf-8

# flake8: noqa
"""
    Document API for Dummies

    A simple API to learn the basics and experiment with documents.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from openapi_client.models.document import Document
from openapi_client.models.document_create import DocumentCreate
from openapi_client.models.document_type import DocumentType
from openapi_client.models.http_validation_error import HTTPValidationError
from openapi_client.models.validation_error import ValidationError
from openapi_client.models.validation_error_loc_inner import ValidationErrorLocInner

