# coding: utf-8

"""
    Document API for Dummies

    A simple API to learn the basics and experiment with documents.

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DocumentType(str, Enum):
    """
    DocumentType
    """

    """
    allowed enum values
    """
    PDF = 'PDF'
    WORD_DOC = 'Word Doc'
    SPREADSHEET = 'Spreadsheet'
    PLAIN_TEXT = 'Plain Text'
    ARCHIVE = 'Archive'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DocumentType from a JSON string"""
        return cls(json.loads(json_str))


