name: Regenerate and Publish Client Package

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out client repository
        uses: actions/checkout@v4

      - name: Download latest openapi.json from server repo
        run: |
          gh release download --repo mykingdomforapawn/api-for-dummies --pattern 'openapi.json' --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate client code from spec
        run: |
          docker run --rm \
            --user $(id -u):$(id -g) \
            -v "${PWD}:/local" \
            openapitools/openapi-generator-cli generate \
              -i /local/openapi.json \
              -g python \
              --package-name api-for-dummies-client \
              -o /local/generated_client

      - name: Enrich Package Metadata
        run: |
          # Change package name to match what you want to publish
          sed -i 's|^NAME = "openapi-client"|NAME = "api-for-dummies-client"|' generated_client/setup.py

          # Add the repository URL for better metadata
          sed -i 's|url="",|url="https://github.com/${{ github.repository }}",|' generated_client/setup.py

          # Print the modified setup.py for debugging
          echo "==== setup.py after modification ===="
          cat generated_client/setup.py

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build Python package
        run: python -m build
        working-directory: ./generated_client

      - name: Publish package to GitHub Packages
        run: |
          echo "Uploading to: https://pypi.pkg.github.com/${{ github.repository }}"
          twine upload --repository-url https://pypi.pkg.github.com/${{ github.repository }} \
            --username __token__ \
            --password ${{ secrets.GITHUB_TOKEN }} \
            dist/*
        working-directory: ./generated_client
